services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"


  nginx:
    image: nginx:1.27.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/shaxzodbek.com/fullchain.pem:/etc/ssl/certs/shaxzodbek.crt:ro
      - /etc/letsencrypt/live/shaxzodbek.com/privkey.pem:/etc/ssl/private/shaxzodbek.key:ro
    depends_on:
      - web
