services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"


  nginx:
    image: nginx:1.27.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - /root/shaxzodbek.com/nginx/ssl:/var/www/certbot:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
