services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"


  nginx:
    image: nginx:1.27.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
