# Generated by Django 5.1.1 on 2024-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
