# Generated by Django 5.1.1 on 2024-10-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cv_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
