# Generated by Django 5.1.1 on 2024-10-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_cv_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=models.TextField(default='soon added'),
            preserve_default=False,
        ),
    ]
