# Generated by Django 5.1.1 on 2024-11-19 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "user_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(blank=True, max_length=256, null=True)),
                ("username", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("is_bot", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("is_premium", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "telegram_user",
                "verbose_name_plural": "telegram_users",
                "db_table": "telegram_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Commands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=256)),
                ("message", models.TextField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands",
                        to="telegrambot.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "user_command",
                "verbose_name_plural": "user_commands",
                "db_table": "user_commands",
                "ordering": ["-created_at"],
            },
        ),
    ]
