# Generated by Django 5.1.1 on 2024-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commands",
            name="command",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="commands",
            name="message",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="commands",
            name="response",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
