# Generated by Django 5.1.1 on 2024-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0003_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="is_bot",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="is_premium",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="language_code",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="last_active",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
