# Generated by Django 5.1.1 on 2024-11-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0005_remove_commands_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="user",
        ),
        migrations.DeleteModel(
            name="Commands",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
