# Generated by Django 5.1.1 on 2024-12-01 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0006_remove_feedback_user_delete_commands_delete_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCommands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="telegrambot.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "user_command",
                "verbose_name_plural": "user_commands",
                "db_table": "user_commands",
                "ordering": ["-created_at"],
            },
        ),
    ]
