# Generated by Django 5.1.1 on 2024-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0007_usercommands"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercommands",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usercommands",
            name="command",
            field=models.CharField(max_length=100),
        ),
    ]
