# Generated by Django 5.1.1 on 2025-01-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cv/aboutMe/%Y/%m/%d/"
                    ),
                ),
                ("extra_data", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "About Me",
                "verbose_name_plural": "About Me",
                "db_table": "about_me",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AboutShe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cv/aboutShe/%Y/%m/%d/"
                    ),
                ),
                ("extra_data", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "About she",
                "verbose_name_plural": "About she",
                "db_table": "about_she",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/articles/%Y/%m/%d"
                    ),
                ),
                ("body", models.TextField()),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="5b0e0623-3573-44c5-8dce-461b069dd82d",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("telegram", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "articles",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "db_table": "author",
                "ordering": ["-first_name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "category",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="CVImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="cv/cvImages/%Y/%m/%d/")),
            ],
            options={
                "verbose_name": "CV Image",
                "verbose_name_plural": "CV Images",
                "db_table": "cv_images",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("who_is_it", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "db_table": "matches",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "ProgrammingLanguage",
                "verbose_name_plural": "ProgrammingLanguages",
                "db_table": "programmingLanguage",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
                "db_table": "technologies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField()),
                ("thumbnail", models.ImageField(upload_to="blog/video/%Y/%m/%d")),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "db_table": "video",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("picture", models.ImageField(upload_to="blog/connection/%Y/%m/%d")),
                ("birth_date", models.DateField()),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("met_address", models.TextField()),
                ("home_address", models.TextField(blank=True, null=True)),
                ("met_at", models.DateTimeField()),
                ("listed", models.BooleanField(default=True)),
                (
                    "who_for_me",
                    models.ManyToManyField(related_name="who_me", to="blog.match"),
                ),
            ],
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
                "db_table": "connections",
                "ordering": ["-birth_date"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("purpose", models.CharField(max_length=255)),
                ("picture", models.ImageField(upload_to="blog/book/%Y/%m/%d")),
                ("book_file", models.FileField(upload_to="blog/files/book/%Y/%m/%d")),
                ("download_count", models.IntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        default="a8493d3a-c1c3-4738-8a86-bf67a9adec93", unique=True
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books_author", to="blog.author"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="books_categories", to="blog.category"
                    ),
                ),
                (
                    "programming_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blog.programminglanguage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "book",
                "ordering": ["-title"],
            },
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="cv/cvFiles/%Y/%m/%d/"
                    ),
                ),
                ("path", models.URLField(blank=True, null=True)),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("is_working", models.BooleanField(default=False)),
                (
                    "picture",
                    models.ManyToManyField(
                        related_name="cv_pictures", to="blog.cvimages"
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="cv_pictures", to="blog.technology"
                    ),
                ),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
                "db_table": "cvs",
                "ordering": ["-created_at"],
            },
        ),
    ]
