# Generated by Django 5.1.1 on 2025-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="663e03d5-9494-4a3e-9934-c34249495fbf",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                default="11def605-2c51-44e7-85a3-181f6a93eed2", unique=True
            ),
        ),
    ]
