# Generated by Django 5.1.1 on 2024-10-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='telegram',
            field=models.BooleanField(default=False),
        ),
    ]
