# Generated by Django 5.1.1 on 2024-12-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_aboutme_cvimages_technology_cv"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutShe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cv/aboutShe/%Y/%m/%d/"
                    ),
                ),
                ("extra_data", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "About she",
                "verbose_name_plural": "About she",
                "db_table": "about_she",
                "ordering": ["-created_at"],
            },
        ),
    ]
