# Generated by Django 5.1.1 on 2025-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_slug_alter_book_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="book",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="book",
            name="programming_language",
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="ProgrammingLanguage",
        ),
    ]
