# Generated by Django 5.1.1 on 2024-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_aboutshe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="08c8b3d7-fd2a-48cc-8c0e-0fb9b10c5ebd",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
