# Generated by Django 5.1.1 on 2024-10-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_connection_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='who_for_me',
            field=models.ManyToManyField(related_name='who_me', to='blog.match'),
        ),
    ]
