# Generated by Django 5.1.1 on 2024-12-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="1a51731c-8584-4956-a54a-942dbe111113",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
