# Generated by Django 5.1.1 on 2024-12-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="93a82441-a4e2-4d0c-9022-55a20ca2bb26",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
