# Generated by Django 5.1.1 on 2024-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="67117929-4d55-4422-ab1e-9169520d8d52",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
