# Generated by Django 5.1.1 on 2024-12-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="376a268d-e0ee-4804-8d8b-500447539b08",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
