# Generated by Django 5.1.1 on 2024-12-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_book_download_count_alter_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="2730fad6-4721-4ebe-a64c-f18db35f100b",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
