# Generated by Django 5.1.1 on 2024-12-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_video_description_alter_article_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
        migrations.RenameField(
            model_name="video",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="fa6c16cf-513a-42c5-8994-3382a0779735",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
