# Generated by Django 5.1.1 on 2024-12-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_video_options_rename_created_video_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="authors",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="category",
            new_name="categories",
        ),
        migrations.RemoveField(
            model_name="book",
            name="download_count",
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="79c5bf6e-0efa-4b91-8940-485860976dbe",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
