# Generated by Django 5.1.1 on 2024-12-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_rename_author_book_authors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="673d52e9-b14b-44c6-aca7-d497dd7f71ee",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
