# Generated by Django 5.1.1 on 2024-12-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_rename_book_book_book_file_alter_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                default="265c7606-502c-4d32-bc9c-f0794ef8c254", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="b725603f-e89c-4037-b816-a86e82c1a345",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
