# Generated by Django 5.1.1 on 2024-12-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_book_slug_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="907507cc-84da-4446-bdd4-44e2dd421971",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                default="b6ecfe93-f732-4f06-91d3-f7e57cd25800", unique=True
            ),
        ),
    ]
