# Generated by Django 5.1.1 on 2024-12-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_article_slug_alter_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="99eef422-745e-4c5c-993d-c1d03d5b7914",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                default="231f995e-da69-4c91-8ae2-b4f7f37cdd3b", unique=True
            ),
        ),
    ]
