# Generated by Django 5.1.1 on 2024-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_article_slug_alter_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="5fabb820-a53c-46f2-95ed-7efb776580eb",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                default="986ec4a1-5a81-4b6b-ab40-1962967243dc", unique=True
            ),
        ),
    ]
