# Generated by Django 5.1.1 on 2024-12-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_article_slug_alter_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="12e7083e-4803-436a-ae2f-6c9c372399a6",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                default="c2c92868-0688-490e-88eb-f05b76c53360", unique=True
            ),
        ),
    ]
