# Generated by Django 5.1.1 on 2024-12-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_article_slug_alter_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="ce112eb3-ab14-4f6e-ae5c-720138f342f6",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                default="b24cb7b5-167c-4db8-b260-09528b83ea23", unique=True
            ),
        ),
    ]
