# Generated by Django 5.1.1 on 2024-11-19 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("output", models.TextField()),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Example",
                "verbose_name_plural": "Examples",
                "db_table": "Example",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="problems/files/%Y/%m/%d/")),
            ],
            options={
                "verbose_name": "Files",
                "verbose_name_plural": "Files",
                "db_table": "Files",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Hint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hint", models.TextField()),
            ],
            options={
                "verbose_name": "Hint",
                "verbose_name_plural": "Hints",
                "db_table": "Hint",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="problems/%Y/%m/%d/")),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "db_table": "Img",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "db_table": "Theme",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "db_table": "Topic",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                ("solution", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "examples",
                    models.ManyToManyField(
                        blank=True, related_name="problems", to="problems.example"
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True, related_name="problems_files", to="problems.files"
                    ),
                ),
                (
                    "hints",
                    models.ManyToManyField(
                        blank=True, related_name="problems", to="problems.hint"
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True, related_name="problems", to="problems.img"
                    ),
                ),
                (
                    "solved_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="solved_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.ManyToManyField(
                        blank=True, related_name="theme_problems", to="problems.theme"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="problems", to="problems.topic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem",
                "verbose_name_plural": "Problems",
                "db_table": "Problem",
                "ordering": ("-created",),
            },
        ),
    ]
