# Generated by Django 5.1.1 on 2024-12-01 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True,
                        help_text="Total execution time in seconds",
                        null=True,
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        blank=True, help_text="Peak memory usage in MB", null=True
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "db_table": "Submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.TextField(help_text="Input data for the test case"),
                ),
                (
                    "expected_output",
                    models.TextField(help_text="Expected output for the test case"),
                ),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a sample test case visible to users?",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Order of test case execution"
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Case",
                "verbose_name_plural": "Test Cases",
                "db_table": "TestCase",
                "ordering": ["problem", "order"],
                "unique_together": {("problem", "order")},
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                (
                    "execution_time",
                    models.FloatField(help_text="Execution time in seconds"),
                ),
                ("memory_usage", models.FloatField(help_text="Memory usage in MB")),
                ("output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="problems.submission",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.testcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Result",
                "verbose_name_plural": "Test Results",
                "db_table": "TestResult",
                "ordering": ["test_case__order"],
            },
        ),
        migrations.CreateModel(
            name="UserProblemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_solved", models.BooleanField(default=False)),
                ("attempts_count", models.PositiveIntegerField(default=0)),
                ("first_solved_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(auto_now=True)),
                ("best_execution_time", models.FloatField(blank=True, null=True)),
                ("best_memory_usage", models.FloatField(blank=True, null=True)),
                ("favorite", models.BooleanField(default=False)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_statuses",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Problem Status",
                "verbose_name_plural": "User Problem Statuses",
                "db_table": "UserProblemStatus",
                "ordering": ["-last_attempted_at"],
                "unique_together": {("user", "problem")},
            },
        ),
    ]
