# Generated by Django 5.1.1 on 2024-11-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="examples",
            field=models.ManyToManyField(
                blank=True, related_name="problem_examples", to="problems.example"
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="hints",
            field=models.ManyToManyField(
                blank=True, related_name="problem_hints", to="problems.hint"
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="problem_images", to="problems.img"
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="problem_topics", to="problems.topic"
            ),
        ),
    ]
