# Generated by Django 5.1.1 on 2024-12-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_submission_testcase_testresult_userproblemstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="submission",
        ),
        migrations.AlterUniqueTogether(
            name="testcase",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="problem",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="test_case",
        ),
        migrations.AlterUniqueTogether(
            name="userproblemstatus",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userproblemstatus",
            name="problem",
        ),
        migrations.RemoveField(
            model_name="userproblemstatus",
            name="user",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
        migrations.DeleteModel(
            name="TestCase",
        ),
        migrations.DeleteModel(
            name="TestResult",
        ),
        migrations.DeleteModel(
            name="UserProblemStatus",
        ),
    ]
