# Generated by Django 5.1.1 on 2024-11-16 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_alter_problem_examples_alter_problem_hints_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="solved_users",
            field=models.ManyToManyField(
                blank=True, related_name="solved_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
