# Generated by Django 5.1.1 on 2024-10-27 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='initial_code',
            field=models.TextField(default='def solution(input):\n    # Write your code here\n    pass'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='essential.problem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
