# Generated by Django 5.1.1 on 2024-11-29 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 29, 5, 47, 3, 663115, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
