# Generated by Django 5.1.1 on 2024-11-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers_alter_user_groups_and_more"),
        ("problems", "0002_alter_problem_examples_alter_problem_hints_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="solved_problems",
            field=models.ManyToManyField(
                blank=True, related_name="solved_problems", to="problems.problem"
            ),
        ),
    ]
