# Generated by Django 5.1.1 on 2024-11-29 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_onetimepassword_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 29, 6, 50, 48, 906478, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
