# Generated by Django 5.1.1 on 2024-11-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_solved_problems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="solved_problems",
        ),
    ]
