# Generated by Django 5.1.1 on 2024-12-01 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_onetimepassword_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 1, 9, 11, 46, 227599, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
