# Generated by Django 5.1.1 on 2024-12-01 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_rename_name_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 1, 18, 26, 54, 182549, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
