# Generated by Django 5.1.1 on 2024-12-01 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_alter_onetimepassword_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 1, 18, 27, 16, 923142, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
