# Generated by Django 5.1.1 on 2024-12-01 18:44

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_alter_onetimepassword_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/%Y/%M/%d"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, default=uuid.uuid4, max_length=150, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 1, 18, 49, 28, 827936, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
