# Generated by Django 5.1.1 on 2024-12-12 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_user_data_of_birth_user_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 12, 14, 43, 16, 111352, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
