# Generated by Django 5.1.1 on 2024-12-13 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_alter_onetimepassword_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 10, 36, 21, 467151, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
