# Generated by Django 5.1.1 on 2024-12-13 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_alter_onetimepassword_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 14, 35, 28, 273407, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
