# Generated by Django 5.1.1 on 2024-12-17 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_onetimepassword_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 17, 20, 14, 47, 394172, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
