# Generated by Django 5.1.1 on 2024-12-18 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0027_alter_onetimepassword_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 18, 10, 15, 17, 527380, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
