# Generated by Django 5.1.1 on 2024-12-18 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_alter_onetimepassword_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimepassword",
            name="purpose",
            field=models.CharField(default="verification", max_length=20),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expiry",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
