# Generated by Django 5.1.1 on 2024-12-20 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0029_onetimepassword_purpose_alter_onetimepassword_expiry_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("1848a5e0-5e03-4f8a-8627-64e02afd8184"),
                max_length=160,
                unique=True,
            ),
        ),
    ]
