# Generated by Django 5.1.1 on 2024-12-20 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0030_alter_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("74860c9e-f6e4-4206-971e-a551e4b770cf"),
                max_length=160,
                unique=True,
            ),
        ),
    ]
