# Generated by Django 5.1.6 on 2025-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/certificate/%Y/%m/%d"
                    ),
                ),
                ("took_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "certification",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="blog/cv/")),
            ],
            options={
                "db_table": "cv",
                "ordering": ["-file"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/education/%Y/%m/%d"
                    ),
                ),
                ("started_from", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(auto_now=True)),
                ("field", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "education",
                "ordering": ["-started_from"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content1", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/posts/%Y/%m/%d"
                    ),
                ),
                ("content2", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("visible", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/programming_languages/%Y/%m/%d",
                    ),
                ),
                ("knowing_percentage", models.FloatField(default=0)),
                ("started_from", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "programming_languages",
                "ordering": ["-started_from"],
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "db_table": "types",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/projects/%Y/%m/%d"
                    ),
                ),
                ("link_to_project", models.URLField(blank=True, null=True)),
                ("github_link", models.URLField(blank=True, null=True)),
                ("started_from", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                (
                    "programming_languages",
                    models.ManyToManyField(to="blog.programminglanguage"),
                ),
                ("type", models.ManyToManyField(to="blog.type")),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-started_from"],
            },
        ),
    ]
