# Generated by Django 5.1.6 on 2025-03-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programminglanguage",
            old_name="picture",
            new_name="image",
        ),
    ]
