# Generated by Django 5.1.6 on 2025-03-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Post",
        ),
        migrations.AlterModelTable(
            name="post",
            table="posts",
        ),
    ]
