# Generated by Django 5.1.6 on 2025-03-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="ended_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="education",
            name="started_from",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="programminglanguage",
            name="started_from",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
