# Generated by Django 5.1.6 on 2025-03-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_type_project_github_link_project_link_to_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programminglanguage",
            name="knowing_percentage",
            field=models.FloatField(default=0),
        ),
    ]
