# Generated by Django 5.1.6 on 2025-03-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_programminglanguage_knowing_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="blog/cv/%Y/%m/%d"
                    ),
                ),
            ],
            options={
                "db_table": "cv",
                "ordering": ["-file"],
            },
        ),
    ]
