# Generated by Django 5.1.6 on 2025-03-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="blog/cv/"),
        ),
    ]
