# Generated by Django 5.1.1 on 2024-11-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="api/math/%Y/%m/%d"
                    ),
                ),
                ("option1", models.CharField(max_length=100)),
                ("option2", models.CharField(blank=True, max_length=100, null=True)),
                ("option3", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("taken_book", models.CharField(blank=True, max_length=100, null=True)),
                ("theme", models.CharField(blank=True, max_length=100, null=True)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Math",
                "verbose_name_plural": "Maths",
                "db_table": "Math",
                "unique_together": {("option1", "option2", "option3", "answer")},
            },
        ),
    ]
