name: Django CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Copy .env file
        run: |
          cp core/.env.test core/.env

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r core/requirements.txt

      - name: Run Tests
        run: |
          cd core
          python manage.py test blog
